### ISSUE TITLE
Rivagan only supports 32 bits watermark now

### ISSUE THREAD

**Issue by llbbcc** [ShieldMnt/invisible-watermark#29]
Hi!
Thanks for your great work! How can I train a Rivagan that supports a 64-bit watermark?

**Comment by llbbcc** [comment]
Thanks for your great work again! For this question, I've already gotten my answer [here](https://github.com/DAI-Lab/RivaGAN/tree/master).

**Comment by asdcaszc** [comment]
> Thanks for your great work again! For this question, I've already gotten my answer [here](https://github.com/DAI-Lab/RivaGAN/tree/master).

Hi, do you know how to train the a 64-bit image watermark? The link seems like a video watermark and they did not provide the neural network pth file.
