### ISSUE TITLE
Image file size decreases

### ISSUE THREAD

**Issue by chiragsanghvi1** [ShieldMnt/invisible-watermark#33]
Hi, 
What I observed is the image file size before adding invisible watermark is `2.7 mb.` 
`Image = 1816 × 1382`. After adding watermark text of` length = 41. ` 

```       # Encode watermark 
        encoder = WatermarkEncoder()
        encoder.set_watermark('bytes', invisible_watermark_text.encode('utf-8'))
        bgr_encoded = encoder.encode(cv2_img_obj, 'dwtDctSvd')
        # print("Invisible watermark added to the image")

        # Convert back to OpenCV format
        _, encoded_img = cv2.imencode('.jpeg', bgr_encoded)
```

The file size reduces to `0.35 mb`

any idea why and how can I retain the original file size?

**Comment by uioo1** [comment]
If the original image is in png format, encoding the watermark and saving it in JPEG format will compress it and reduce its size. 
`_, encoded_img = cv2.imencode('.png', bgr_encoded)`
By writing code like this, you can maintain the file size.

**Comment by chiragsanghvi1** [comment]
This works. Thanks @uioo1 💯
